author: K0Gs
description: A "block" animation plugin;
database: false
main: com.k0gshole.MoveIt.MoveItMain
name: MoveIt
version: '1.0'
depend: [Vault]
commands:
   moveit:     
      description: Open The Gui.
      usage: /moveit create [animation, frame, block] <name>, /moveit delete [animation or frame], /moveit list [animation or frame], /moveit select [animation or frame] <name or number>, /moveit play <name>, /moveit stop <name>

